import './globals.css'
import type { Metadata } from 'next'
import {NextIntlClientProvider} from 'next-intl';
import {notFound} from 'next/navigation';
import Header from '@/global/components/Header';
import Footer from '@/global/components/footer/Footer';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

 
export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'ar'}];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children, params: {locale}
}: {
  children: React.ReactNode,
    params: { locale: string };

}) {

    let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@100;200;300;400;500;600;700&display=swap" />
        <link rel="stylesheet" href="../[locale]/campaigns/components/previousCampaigns/timeline/style.css" />  
      </head>
      <body className="bg-light font-ibm-plex-sans-arabic">
      <NextIntlClientProvider locale={locale} messages={messages}>
        <Header/>
        {children}
        <Footer/>
      </NextIntlClientProvider>
        </body>
    </html>
  )
}
